### ISSUE TITLE
RDataFrame Python vs. C++ (single-thread)

### ISSUE THREAD

**Issue by peremato** [Moelf/UnROOT_RDataFrame_MiniBenchmark#3]
In this benchmark the comparison is done between Julia and PyRDF (RDataFrame in Python), which is probably correct if we want to compare analysis environments/ecosystems. However if we want to compare Julia with C++ we should run RDataFrame in C++. @eguiraud has re-run the benchmark in his laptop with different settings. The C++ file is attached. Here are the results:

(all single-threaded)
+ Python RDF: 41.8s 
+ ACLiC'd header: 37.6s
+ injecting #pragma cling optimize O3 in RDF jitted code: 34s 
+ C++ RDF (still jitting Filters/Defines): 32s 
+ Julia: 28.60s 
+ C++ RDF (fully compiled, no jitting): 19s 

The numbers between Python RDF and Julia are somehow compatible with the previous measurements, but the difference Python RDF and C++ RDF is a factor 2. 

[RDataFrame_benchmark.cpp](https://github.com/Moelf/UnROOT_RDataFrame_MiniBenchmark/files/7143994/RDataFrame_benchmark.cpp.txt)

**Comment by Moelf** [comment]
~~My take away for now from:~~
>- C++ RDF (still jitting Filters/Defines): 32s
>- Julia: 28.60s
>- C++ RDF (fully compiled, no jitting): 19s

~~is that we're not too bad as it stands. Since the last option, as noted, means 0 interactivity and compilation time between each iteration during the development stage.~~

The difference is still worth investigating because this looks like C++ is faster than itself if you just write a normal for-loop, something smart is going on for RDF, will investigate.

Edit: investigation shows ROOT is using all cores for multi-threading thus faster.

**Comment by Moelf** [comment]
```
$ g++ RDataFrame_benchmark_compiled.cpp `root-config --cflags --glibs` -o compiled_run
```

uploaded file to repo: https://github.com/Moelf/UnROOT_RDataFrame_MiniBenchmark/blob/master/RDataFrame_benchmark_compiled.cpp. Could use a makefile

**Comment by Moelf** [comment]
https://github.com/Moelf/UnROOT_RDataFrame_MiniBenchmark/blob/4ee180064dc1ca95cce6b36b031efd6629b7988f/RDataFrame_benchmark_compiled.cpp#L8

this is enabling multi-threading, change this line to:
```diff
diff --git a/RDataFrame_benchmark_compiled.cpp b/RDataFrame_benchmark_compiled.cpp
index 6490268..934f518 100644
--- a/RDataFrame_benchmark_compiled.cpp
+++ b/RDataFrame_benchmark_compiled.cpp
@@ -5,7 +5,7 @@
 #include <TStopwatch.h>
 
 int main() {
-   ROOT::EnableImplicitMT();
+   ROOT::EnableImplicitMT(1);
   auto df_bkg_4mu = ROOT::RDataFrame("Events", "Run2012BC_DoubleMuParked_Muons.root");
 
   // Filter interesting events
```

made the time go from `11s` to `36s` for me locally.

can you confirm @eguiraud this was a typo? I can see before it was clearly using all cores on this machine.

![image](https://user-images.githubusercontent.com/5306213/132885957-3742980f-348e-41ec-bbb9-a3e87e62ab61.png)

**Comment by eguiraud** [comment]
Hi,
this is how it works (also see [the docs](https://root.cern/doc/master/namespaceROOT.html#a06f2b8b216b615e5abbc872c9feff40f)):
- single-thread: no `EnableImplicitMT()`, aka `// EnableImplicitMT()`
- multi-thread with a thread-pool of size 1: `EnableImplicitMT(1)` (note that this is typically a bit slower than single-thread!!)
- multi-thread with a thread-pool of size equal to the logical cores of the machine: `EnableImplicitMT()`

The times reported above are with the single-thread option above, then switching to 4 threads reduces the runtime to 5s on my laptop.

Also note that in your compilation command above (`g++ RDataFrame_benchmark_compiled.cpp `root-config --cflags --glibs` -o compiled_run`) you are missing the (crucial!) optimization flag `-O2`.

**Comment by eguiraud** [comment]
Unrelated, when running the comparison I noticed the output histogram in the RDF code had 80485 entries while the Julia notebook reports 80487 entries, not sure if that's ok.

**Comment by Moelf** [comment]
Thanks for the correction,
```diff
@@ -5,7 +5,6 @@
 #include <TStopwatch.h>
 
 int main() {
-   ROOT::EnableImplicitMT();
   auto df_bkg_4mu = ROOT::RDataFrame("Events", "Run2012BC_DoubleMuParked_Muons.root");
 
   // Filter interesting events
```
with: ```g++ RDataFrame_benchmark_compiled.cpp -O2 `root-config --cflags --glibs` -o compiled_run```

gives me `20s` locally, and Julia time is `21s`, this makes much more sense.

**Comment by Moelf** [comment]
>The times reported above are with the single-thread option above, then switching to 4 threads reduces the runtime to 5s on my laptop.

this is pretty hard to believe (the single-thread part), maybe some hard drive cache is involved? Also, can you pull this repo again with UnROOT 0.5.1? (and of course, use Julia 1.7 since `Zlib` was recently put into stdlibs)

For me 4-threads reduces time from `20s` to `13s` on `CPU: Intel(R) Xeon(R) W-2265 CPU @ 3.50GHz` and a HDD.

**Comment by eguiraud** [comment]
Which numbers are surprising exactly? I just pulled the latest version of this repo and re-ran with UnROOT 0.5.1 (but still Julia 1.6.2, that's what I could easily set up) and it's 23.8s (pretty stable across runs after the first) for the Julia notebook as reported by the cell with the `@time` and 20s for `RDataFrame_benchmark_compiled.cpp` compiled with `-O2` (after removing `EnableImplicitMT()`). Adding `EnableImplicitMT(4)` at the beginning of `RDataFrame_benchmark_compiled.cpp` gets me  to 5s.

I'm using ROOT's master branch and all these runs are with the input file warm in the filesystem cache. The CPU is `Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz`.

**Comment by Moelf** [comment]
oh, I thought:
>The times reported above

was referring to Pere's number where Julia is 28s and C++ compiled is 19s. If you're seeing `20s` vs. `23.8s` then it's fine. Moving to Julia 1.7 will speed things up a bit but 10% is not as surprising as 30%.

**Comment by eguiraud** [comment]
28s is what I got yesterday with UnROOT 0.5.0 -- tried again now and that's still the case, it seems to be a difference between 0.5.0 and 0.5.1.

**Comment by Moelf** [comment]
yes, we fixed a few places where memory was wasted in 0.5.1. Are you also running on a limited memory ~8GB system like Philippe?

**Comment by eguiraud** [comment]
32GB :man_shrugging:

**Comment by Moelf** [comment]
well, I take it's fixed in 0.5.1 since the time is also stable? Guess this issue is solved then, you could try 1.7 and we could all try multi-threading timing in a different thread.

**Comment by Moelf** [comment]
continuing multi-threading discussion in:
https://github.com/Moelf/UnROOT_RDataFrame_MiniBenchmark/issues/4

leaving this open in case people find disagreement again.

**Comment by Moelf** [comment]
putting into scripts for easy re-run:
https://github.com/Moelf/UnROOT_RDataFrame_MiniBenchmark/tree/master/composite_benchmarks

**Comment by Moelf** [comment]
@peremato I have updated the repo, and somehow after a year of random updates, we're now squarely faster than ROOT? can you sanity check me when you have time thanks!
