### ISSUE TITLE
root path not found 

### ISSUE THREAD

**Issue by liulc-tech-star** [Moelf/UnROOT_RDataFrame_MiniBenchmark#7]
Hi,

the .root path seems not found.

http://opendata.web.cern.ch/record/12341/files

**Comment by Moelf** [comment]
- http://opendata.web.cern.ch/record/12341
- http://opendata.web.cern.ch/record/12341/files/Run2012BC_DoubleMuParked_Muons.root


the first link is what I posted, and when you click Download it brings you to the second one, idk where you ever saw that `/files` link

**Comment by liulc-tech-star** [comment]
Dear Ling,

Thanks for the reply.
I have clicked the 
http://opendata.web.cern.ch/record/12341/files/Run2012BC_DoubleMuParked_Muons.root
But, the connection in my region(China) doesn't work, always interrupt, even I used the "ladder".

So, may I request you to kindly post the .root on your Git or to my e-mail as an attachment?

Many thanks!

Best reagrds,
Liangchen Liu




***@***.***
 
From: Jerry Ling
Date: 2023-01-10 23:43
To: Moelf/UnROOT_RDataFrame_MiniBenchmark
CC: liulcprc; State change
Subject: Re: [Moelf/UnROOT_RDataFrame_MiniBenchmark] root path not found (Issue #7)
http://opendata.web.cern.ch/record/12341
http://opendata.web.cern.ch/record/12341/files/Run2012BC_DoubleMuParked_Muons.root
the first link is what I posted, and when you click Download it brings you to the second one, idk where you ever saw that /files link

**Comment by liulc-tech-star** [comment]
Dear Ling,

I have changed the network and got the root file.

Thank you!

Best reagrds,
Liangchen Liu






***@***.***
 
From: ***@***.***
Date: 2023-01-11 13:53
To: Moelf/UnROOT_RDataFrame_MiniBenchmark
Subject: Re: Re: [Moelf/UnROOT_RDataFrame_MiniBenchmark] root path not found (Issue #7)
Dear Ling,

Thanks for the reply.
I have clicked the 
http://opendata.web.cern.ch/record/12341/files/Run2012BC_DoubleMuParked_Muons.root
But, the connection in my region(China) doesn't work, always interrupt, even I used the "ladder".

So, may I request you to kindly post the .root on your Git or to my e-mail as an attachment?

Many thanks!

Best reagrds,
Liangchen Liu




***@***.***
 
From: Jerry Ling
Date: 2023-01-10 23:43
To: Moelf/UnROOT_RDataFrame_MiniBenchmark
CC: liulcprc; State change
Subject: Re: [Moelf/UnROOT_RDataFrame_MiniBenchmark] root path not found (Issue #7)
http://opendata.web.cern.ch/record/12341
http://opendata.web.cern.ch/record/12341/files/Run2012BC_DoubleMuParked_Muons.root
the first link is what I posted, and when you click Download it brings you to the second one, idk where you ever saw that /files link
